export const profile = {
  name: "Jackson Eduardo",
  headline: "Desenvolvedor",
  location: "Brasil",
  bio: "Desenvolvedor .NET/ASP/MAUI apaixonado por criar soluções inteligentes que simplificam problemas reais.",
  summary:
    "Sou desenvolvedor .NET com formação técnica e tecnológica em Análise e Desenvolvimento de Sistemas. Atuo com foco em arquitetura, padrões de projeto e boas práticas que garantem aplicações escaláveis e de alta qualidade. Trabalho com ASP.NET, .NET MAUI e desenvolvimento multiplataforma, sempre priorizando organização, desempenho e a entrega de soluções robustas que gerem valor real para usuários e empresas.",
  stack: [
    "REST APIs",
    ".NET",
    "ASP.NET Core",
    ".NET MAUI",
    "Entity Framework Core",
    "C#",
    "SQL Server",
    "OracleBD",
    "Azure",
    "Docker",
    "Git",
    "Phython",
    "TypeScript",
    "NodeJS",
  ],
  social: {
    github: "https://github.com/euj4ckson",
    linkedin: "",
    email: "jacksonduardo6@gmail.com",
    whatsapp: "",
  },
  resumeUrl: "/resume.pdf",
};
